default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: db
  port: 3306

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
