default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  database: db
  host: <%= ENV['DB_HOST'] %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  port: 3306
  # socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
