# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby         '3.0.2'
gem 'rails', '~> 6.1'

gem 'active_storage_validations', '0.6.1' # ActiveStorageのバリデーション
gem 'aws-sdk-s3', '~> 1.104'              # aws S3
gem 'bcrypt',     '3.1.16'                # ハッシュ値生成
gem 'bootsnap',   '1.4.5', require: false # rails起動時間の最適化
gem 'puma',       '5.0'                   # APサーバ
gem 'rack-cors',  '1.1.1'                 # CORS設定
gem 'rakuten_web_service'                 # 楽天APIの利用

group :development, :test do
  gem 'byebug',      '11.1.3', platforms: %i[mri mingw x64_mingw] # デバック
  gem 'capybara',    '~> 3.23'                                    # 統合テスト
  gem 'factory_bot_rails', '~> 6.2'                               # bot
  gem 'rspec-rails', '5.0.2'                                      # テスト
  gem 'sqlite3',     '1.4.2'                                      # DB
end

group :development do
  gem 'listen',                '3.3'
  gem 'rack-mini-profiler',    '2.3.3'                  # パフォーマンス計測
  gem 'rubocop',               '1.21.0', require: false # コードチェック
  gem 'spring',                '2.1.1'                  # preloader
  gem 'spring-watcher-listen', '2.0.1'                  # FS検知方法:listen
end

group :production do
  gem 'mysql2', '0.5.3' # DB
end
